### ISSUE TITLE
[Feature-Request] incomingFilter for different status

### ISSUE THREAD

**Issue by MZerbe** [AxisCommunications/backstage-plugins#119]
### Describe the feature

At present, the `incomingFilter` in the jira-dashboard-backend plugin only searches for tickets with the status `new`. This limits the plugin's usability in Jira workflows where sometimes the initial status of tickets is not `new`, but something else like `To Do`.  

To enhance the plugin's flexibility, it would be beneficial to introduce an optional annotation for the "incoming issues" status. This annotation would allow users to specify the name of the status for incoming issues.
For instance:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # ...
  annotations:
    jira.com/incoming-issues: value  # optional: The name of the status for incoming issues e.g. 'To Do'
```

### Added value

This feature would improve the usability of the frontend plugin.

### Additional context

<img width="740" alt="image" src="https://github.com/AxisCommunications/backstage-plugins/assets/43886678/bb4e39ed-55fd-46d1-bc7d-0cc234d39632">

https://github.com/AxisCommunications/backstage-plugins/blob/ce0637c46b8e96491a419a619dd76b69dc61b967/plugins/jira-dashboard-backend/src/filters.ts#L18
