### ISSUE TITLE
How should token look like?

### ISSUE THREAD

**Issue by Rades98** [AxisCommunications/backstage-plugins#282]
There doesn’t seem to be any discussion regarding this, so I’m opening it as an issue. Could someone confirm the correct format for the token? Should it be `<email:PAT>` encoded in Base64?

Here’s what I’ve tried so far:

- Plain Personal Access Token (PAT)
- Base64-encoded string in the format Basic `<base64(email:PAT)>`
- `email:PAT` directly

None of these approaches worked, and all resulted in a 404 Not Found error. Additionally, it’s challenging to debug as there’s no log of the actual endpoint being called.
Error:
```
{
  "error": {
    "name": "Error",
    "message": "Request failed with status 404 Not Found, {\n  \"error\": \"No Jira project found with key IKS\"\n}"
  },
  "response": {
    "statusCode": 404
  }
}
```

app-config.yaml
```
jiraDashboard:
  instances:
    - name: default
      token: Basic <base64Encoded>
      baseUrl: https://myOrg.atlassian.net/rest/api/3
```
annotation in catalog-info.yaml of my service:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: iksapi
  description: IKS API
  annotations:
    ...
    jira.com/project-key: IKS
 specs:
   ...
```

Is there something I’m missing regarding the token format or the configuration? 

I also tested calling the endpoint directly via Postman using Basic Auth, and it worked perfectly. Apologies for my confusion, and thanks in advance for your help!

**Comment by anicke** [comment]
If you are using the "non-cloud" version of Jira you can use the PAT directly like:

```
jiraDashboard:
  instances:
    - name: default
      token: Basic <PAT>
      baseUrl: https://myOrg.atlassian.net/rest/api/3
```
