### ISSUE TITLE
Not all components are showing the Jira menu item

### ISSUE THREAD

**Issue by Cord-Thomas** [AxisCommunications/backstage-plugins#293]
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

Working in Jira Data Center v10.3.5

I have recently installed the Jira plugin. I applied the annotations to a handful of repository catalog-info.yaml files. The Jira Dashboard menu is only showing up in a few of the catalog pages:

works (shows up in menu):

```
apiVersion: backstage.io/v1alpha1

kind: Component

metadata:
    name: some-data-pipeline
    description: placeholder
    annotations:
        backstage.io/repository: https://github...
        backstage.io/source-location: url:https://github....
        jira.com/project-key: DST
        jira.com/components: DATTR
...
```

does not work:

```
apiVersion: backstage.io/v1alpha1

kind: Component

metadata:
    name: colloq-backend
    description: Description of this component
    annotations:
        backstage.io/repository: https://code...
        backstage.io/source-location: url:https://code....
        jira.com/project-key: DST
        jira.com/components: Colloq
...
```

### To reproduce

Create project DST
Create components Colloq and DATTR

Add jira.com annotations to catalog-info.yaml files

### Screenshots

Error:  jira-dashboard error Could not find Jira project DST: Failed to get project info for project key DST with error: Request failed with status code 404: Not Found

### Environment

- Axis device model: [e.g. Q1615 Mk III]
- Axis device firmware version: [e.g. 10.5]
- Stack trace or logs: [e.g. Axis device system logs]
- OS and version: [e.g. macOS v12.2.1, Ubuntu 20.04 LTS, Windows build 21996.1]
- Version: [version of the application, SDK, runtime environment, package manager, interpreter, compiler, depending on what seems relevant]
